### ISSUE TITLE
JSON object must be str, bytes or bytearray, not 'OrderedDict'

### ISSUE THREAD

**Issue by pwnchaurasia** [rpkilby/jsonfield2#10]
Hi I am getting error when doing the migration.
`JSON object must be str, bytes or bytearray, not 'OrderedDict'`

I have to add and Json Field.
My actual data looks like this.
`
{"_id":"5dfa0f12024849a16fd1169d","domain_name":"mmdd2.asia","registrar_info":{"name":"ASIA Registry R6-ASIA (700001)|PDR Ltd. d/b/a PublicDomainRegistry.com R28-ASIA (303)","whois_server":"","iana_id":"303"},"contact_email":"webproxy24@gmail.com","name_servers":["NS1.IR-HOST.ORG","NS2.IR-HOST.ORG"],"created_date":"","updated_date":"14-Apr-2014 20:50:06 UTC","expiry_date":"13-Feb-2015 12:27:11 UTC","domain_status":["clientTransferProhibited"],"audit_updated_date":"2014-04-17 07:00:00 UTC","registrant_contacts":{"email":"webproxy24@gmail.com","name":"John Newton","organization":"DomainTools","address":"1570 Elliot Avenue","city":"Seattle","state":"Washington","zip":"98119","country":"UNITED STATES","fax":"","fax_ext":"","telephone":"12065098794.0","telephone_ext":""},"administrative_contacts":{"email":"webproxy24@gmail.com","name":"John Newton","organization":"DomainTools","address":"1570 Elliot Avenue","city":"Seattle","state":"Washington","zip":"98119","country":"UNITED STATES","fax":"","fax_ext":"","telephone":"12065098794.0","telephone_ext":""},"billing_contacts":{"email":"webproxy24@gmail.com","name":"John Newton","organization":"DomainTools","address":"1570 Elliot Avenue","city":"Seattle","state":"Washington","zip":"98119","country":"UNITED STATES","fax":"","fax_ext":"","telephone":"12065098794.0","telephone_ext":""},"technical_contacts":{"email":"compliance@pdrdomains.com","name":"ASIA Domain Manager","organization":"PDR Domains Solutions Private Limited","address":"101/102, Osia Friendship,Gaothan Lane No. 4, Andheri (West)","city":"Mumbai","state":"Maharashtra","zip":"400058","country":"INDIA","fax":"","fax_ext":"","telephone":"912266797550.0","telephone_ext":""},"zone_contacts":{"email":"","name":"","organization":"","address":"","city":"","state":"","zip":"","country":"","fax":"","fax_ext":"","telephone":"","telephone_ext":""}}`

Structure

```
domain_name: "mmdd2.asia" String
registrar_info: Object  Object
contact_email: "cchg***24@gmail.com String
name_servers: Array Array
created_date: "" String
updated_date: 14-Apr-2014 20:50:06 UTC String
expiry_date: "13-Feb-2015 12:27:11 UTC" String
domain_status: Array Array
audit_updated_date: "2014-04-17 07:00:00 UTC" String
registrant_contacts: Object Object
administrative_contacts:  Object Object
billing_contacts: Object Object
technical_contacts: Object Object
zone_contacts: Object Object
```

**Comment by rpkilby** [comment]
> Hi I am getting error when doing the migration.

Can you be more specific. In theory, there should be no migration generated when updating from  `jsonfield`.

**Comment by rjsnh1522** [comment]
My problem is that my data is already defined. so I cant change its structure. I am using djongo to integrate mongodb with it.
My problem is that I have dict fields (Object field) which stores some key value pairs.(structure is defined above).

The dict field is an ordered dict. So i want to know how can i implement it.
