### ISSUE TITLE
Clean method fails on arbitrary string as a valid JSON

### ISSUE THREAD

**Issue by devbis** [rpkilby/jsonfield2#11]
I want to save in JSONField either complex structures such as objects and lists or basic types like str. It should be fully JSON compliant. But I cannot run validation on the model with such JSONField attribute.

```
class Demo(models.Model):
    data = JSONField(blank=True)

demo = Demo.objects.create(data='some test string')
```
we can create a model without validation without any problems.
but when I run validation of the model

```
demo.full_clean()
```
it raises `ValidationError: {'data': ['Enter valid JSON.']}`
though 'some test string' is a valid JSON

**Comment by rpkilby** [comment]
Hi @devbis. Thanks for the report. It looks like some values work fine (objects/arrays/numbers), but others do not (strings/nulls). I'm looking into this further, but there are complications due to the overlap of this field being both JSON and string-based.

**Comment by rpkilby** [comment]
Okay, I've figured out what's going on and am currently working on the fix. Short version is there's weirdness around the model and form field `to_python` implementations. Both methods are called by the model form, resulting in string values being deserialized twice. `'"foo"'` =>`'foo'` => 💥
