### ISSUE TITLE
repo is not compatible with dmkoch/django-jsonfield

### ISSUE THREAD

**Issue by ofirule** [rpkilby/jsonfield2#8]
python3.5
django==2.0.8

`
root@root:/backend# : python manage.py dumpdata
[.................................                                          ]CommandError: Unable to serialize database: the JSON object must be str, not 'dict'
`

it happens on my DB after I 
1 uninstalled jsonfield, 
2 installed jsonfield2
3 restarted all services (probably not related)
4 ran manage.py dumpdata

**Comment by rpkilby** [comment]
Hi @ofirule. Can you provide more information about the data that's failing to serialize? As is, there really isn't anything actionable here.

**Comment by ofirule** [comment]
It's a dictionary with keys and values, I think every dictionary will work, but I didn't test it.

Maybe I wasn't clear enough at first:
the data was written to DB using 'jsonfield' but after the update to 'jsonfield2' I get the error

**Comment by rpkilby** [comment]
Hi @ofirule. At this point, I am unable to recreate the issue. I created a test project using Django 1.11 and jsonfield using the following data:

```json
{
  "a": [1, 2, 3],
  "b": {"foo": "bar"}
}
```

Running dumpdata with jsonfield, I get:
```json
[{"model": "app.example", "pk": 1, "fields": {"name": "Test", "data": "{\"a\":[1,2,3],\"b\":{\"foo\":\"bar\"}}"}}]
```

I then uninstalled jsonfield, installed jsonfield2<=3.1 (3.1 doesn't support Django 1.11), then reran the `dumpdata` command, getting the following:

```json
[{"model": "app.example", "pk": 1, "fields": {"name": "Test", "data": "{\"a\":[1,2,3],\"b\":{\"foo\":\"bar\"}}"}}]
```

Without more information, I can't really debug this. If you could create a PR with a failing test case, that would be immensely helpful. I think you should be able to indirectly test dumpdata by calling Django's builtin serializers.
