### ISSUE TITLE
Try to request a package name transfer

### ISSUE THREAD

**Issue by Mogost** [rpkilby/jsonfield2#8]
According to [PEP 541](https://www.python.org/dev/peps/pep-0541/) It would be nice to request a transfer. Due to the fact that the project is abandoned by the original owner.

**Comment by rpkilby** [comment]
Okay, I "unforked" jsonfield2, so there shouldn't be any issues transferring django-jsonfield to my GH account.  GH has no process for "unforking", so I had to kind of hack it with the following:
- Make sure local git repo was up-to-date
- Rename the fork to jsonfield2-temp
- Create a bare jsonfield2 repo 
- Push branches/tags from local
    - not necessary to set upstream, since it's already set locally
- Transfer relevant issues from old fork to new repo.

This kind of works, but you lose:
- Repo metadata (watchers, stars, forks) 
- PRs (cannot be transferred like issues)

**Comment by rpkilby** [comment]
Sorry for the noise @dmkoch. The tl;dr of the above is that there shouldn't be any issues transferring the project to my account.

**Comment by Mogost** [comment]
Any progress here?

**Comment by rpkilby** [comment]
I'm currently waiting for an update from @dmkoch.

**Comment by blorenz** [comment]
Happy holidays, @dmkoch.  This is a blocker in an upgrade path to Django 3.0. It appears that @rpkilby is ready to run with it if you can do the handoff.  Thank you.

**Comment by kakulukia** [comment]
ping @dmkoch

**Comment by dgorobets** [comment]
ping @dmkoch

**Comment by kakulukia** [comment]
maybe also ping @rpkilby

**Comment by dmkoch** [comment]
@rpkilby I initiated a transfer to you on Github. Let me know and we can figure out the PyPI transfer too.

**Comment by rpkilby** [comment]
Agh, it already expired. Can you reinitiate the transfer?

I'm also @rpkilby on PyPI, and you should be able to add me as an owner to the project. Also happy to coordinate over email if you want.

**Comment by dmkoch** [comment]
I restarted the GitHub transfer.

**Comment by rpkilby** [comment]
Currently transferring 🙇

**Comment by rpkilby** [comment]
Let me know what you want to do about the PyPI transfer. Here's my profile: https://pypi.org/user/rpkilby/

**Comment by dmkoch** [comment]
@rpkilby I added you as an owner on PyPI.

**Comment by rpkilby** [comment]
Awesome - many thanks for adding me to the project. I'm currently working on a few bugs, but am hoping to cut a new release relatively soon.
