### ISSUE TITLE
JSON not formatted correctly in Django admin

### ISSUE THREAD

**Issue by OskarPersson** [rpkilby/jsonfield2#9]
I've recently upgraded from [django-jsonfield](https://github.com/dmkoch/django-jsonfield) to jsonfield2 and I'm now noticing that JSONFields added in Django admin does not pretty print the data. In django-jsonfield this was made automatically, is there some option I need to do in jsonfield2 to get the same result?

My setup:

* Python 3.7.2
* Django 2.2.8
* jsonfield2 3.1.0

**Comment by OskarPersson** [comment]
Solved by adding `'indent': 2` to `dump_kwargs`, which [django-jsonfield does by default]( https://github.com/dmkoch/django-jsonfield/blob/19b62ed3c02674b2ee3d61353312ffa75be373c4/jsonfield/fields.py#L159)

**Comment by rpkilby** [comment]
Using `dump_kwargs` is not completely correct, as this will affect serialization results too. The correct thing to do is to update the form field so that it renders the value properly. There are a few other bugs related to this, but I'm currently working on a PR.
